### ISSUE TITLE
`imp -i` fails when running in WSL

### ISSUE THREAD

**Issue by Xenfo** [arkane-systems/bottle-imp#18] opened 2022-10-15 13:27 UTC
```
❯ imp -i
Traceback (most recent call last):
  File "/home/xenfo/.asdf/installs/python/3.10.8/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xenfo/.asdf/installs/python/3.10.8/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/bottle-imp/imp/__main__.py", line 10, in <module>
  File "/usr/lib/bottle-imp/imp/helpers.py", line 6, in <module>
ModuleNotFoundError: No module named 'psutil'
```

WSL info:
```
WSL version: 0.70.0.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.674
```

Note: `wsl -e imp -i` works fine

**Comment by cerebrate** [comment] 2022-10-15 18:59
(Note to self: same issue as arkane-systems/genie#272 .)

Your problem here is _asdf_-related. The issue is that _imp_ needs the python package _psutil_, and while most of imp's dependencies are wrapped into the imp executable by _zipapp_, _psutil_ can't be, since it uses a C extension. As such, _imp_'s packaging installs the _python3-psutil_ package for the system python, but that only handles the system python.

I don't have a fix for this at this time. The workaround, though, is to install the _psutil_ package into any python environment you might run _imp_ inside.

**Comment by cerebrate** [comment] 2022-11-01 04:56
No fix at this time (and probably not one possible), but now documented in BUGS section.

**Closed by cerebrate** 2022-11-01 04:56 UTC

**Comment by ron-wolf** [comment] 2024-05-03 20:21
I had the same problem with `imp -u` after I installed [`rye`](https://github.com/astral-sh/rye) and configured it to use the system Python installation by default. I am using Ubuntu 22.04. The solution was to `cd` to my home directory, _then_ run `imp -u`. This comes with the same caveats as https://github.com/arkane-systems/bottle-imp/issues/18#issuecomment-1279809503, namely that it must be done for each virtual env in order to be comprehensive.

**Comment by ron-wolf** [comment] 2024-05-03 20:25
@cerebrate I've done a bit of research, and I don't think there's any portable means of ensuring we're running the system Python env, rather than a virtual env that may or may not have `psutil` installed. However, maybe `imp` can run itself with `PYTHONPATH` set to ensure `psutil` is able to be imported. This is `/usr/lib/python3/dist-packages` on Debian derivatives, for instance. Not sure if this is supported by `zipapp`, though, so the binary might have to be moved under some other directory and then invoked by a shim at `bin/imp`. Thoughts?
